function(find arg1)
  ####
  # Find required library with some cute prints. (find_package wrapper)
  set(PACKAGE "${arg1}")
  find_package("${PACKAGE}" REQUIRED)
  if("${${PACKAGE}_FOUND}")
    message("========================================================================================")
    message("Found package ${PACKAGE}!")
    message(STATUS "Appending ${${PACKAGE}_LIBRARIES} to library list.")
    message(STATUS "Appending ${${PACKAGE}_INCLUDE_DIRS} to header list.")
    add_definitions("-DUSE_${PACKAGE}")
    set(REQUIRED_LIBRARIES "${REQUIRED_LIBRARIES};${${PACKAGE}_LIBRARIES}" PARENT_SCOPE)
    set(REQUIRED_HEADERS "${REQUIRED_HEADERS};${${PACKAGE}_INCLUDE_DIRS}" PARENT_SCOPE)
    message("========================================================================================")
  else()
    message(FATAL_ERROR "Cannot find ${PACKAGE}. Please make sure it is available or try setting ${PACKAGE}_INCLUDE_DIR.")
  endif()
endfunction()
